name = "WeibullParetoDist"
uuid = "efcb490d-de09-481a-82de-9e1304d0eed4"
authors = ["Toshiaki_Asakura"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
